import { Bell, Check, RefreshCw } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useAuth } from '@/context/AuthContext';
import { useNav } from '@/context/NavContext';
import { moverApi, type MoverNotification } from '@/lib/Movers';

export default function MoverNotifications() {
  const { profile } = useAuth(); const { navigate } = useNav();
  const [notifications, setNotifications] = useState<MoverNotification[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { if (!profile?.id || profile.role !== 'mover') return; setLoading(true); try { setNotifications((await moverApi.getNotifications(100)).notifications ?? []); } finally { setLoading(false); } }, [profile?.id, profile?.role]);
  useEffect(() => { void load(); }, [load]);
  const markRead = async (id: string) => { await moverApi.markNotificationRead(id); setNotifications((items) => items.map((n) => n.id === id ? { ...n, read_at: new Date().toISOString() } : n)); };
  if (loading) return <div className="flex min-h-[400px] items-center justify-center"><RefreshCw className="h-7 w-7 animate-spin text-brand-500" /></div>;
  return <div className="mx-auto max-w-4xl px-2 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="mb-6 flex items-start justify-between gap-4"><div><button type="button" onClick={() => navigate('dashboard')} className="text-sm font-medium text-brand-600 hover:underline dark:text-brand-400">← Back to dashboard</button><h1 className="mt-2 text-2xl font-bold text-gray-900 dark:text-white">Notifications</h1><p className="mt-1 text-sm text-gray-500 dark:text-gray-400">Booking, payment and service updates.</p></div><button type="button" onClick={() => void load()} className="btn-secondary inline-flex items-center gap-2 text-sm"><RefreshCw className="h-4 w-4" />Refresh</button></div><div className="card overflow-hidden">{notifications.length === 0 ? <div className="p-10 text-center"><Bell className="mx-auto h-9 w-9 text-gray-400" /><p className="mt-3 text-sm text-gray-500 dark:text-gray-400">No notifications.</p></div> : <div className="divide-y divide-gray-100 dark:divide-brand-800">{notifications.map((notification) => { const bookingId = typeof notification.data?.booking_id === 'string' ? notification.data.booking_id : null; return <div key={notification.id} className={`flex gap-3 p-5 ${notification.read_at ? '' : 'bg-brand-50/50 dark:bg-brand-900/10'}`}><button type="button" onClick={() => bookingId ? navigate('mover-booking-detail', bookingId) : undefined} className="min-w-0 flex-1 text-left"><p className="font-semibold text-gray-900 dark:text-white">{notification.title}</p><p className="mt-1 text-sm text-gray-600 dark:text-gray-400">{notification.message}</p><p className="mt-2 text-xs text-gray-400">{new Date(notification.created_at).toLocaleString()}</p></button>{!notification.read_at && <button type="button" onClick={() => void markRead(notification.id)} aria-label="Mark notification as read" className="rounded-lg p-2 text-brand-600 hover:bg-brand-100 dark:text-brand-400 dark:hover:bg-brand-900/30"><Check className="h-4 w-4" /></button>}</div>; })}</div>}</div></div>;
}
