import { FileText, RefreshCw } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useAuth } from '@/context/AuthContext';
import { useNav } from '@/context/NavContext';
import { moverApi, type MoverInvoice, type MoverPayout } from '@/lib/Movers';

const money = (value: number | null | undefined) => `KES ${(value ?? 0).toLocaleString()}`;

export default function MoverInvoices() {
  const { profile } = useAuth(); const { navigate } = useNav();
  const [invoices, setInvoices] = useState<MoverInvoice[]>([]); const [payouts, setPayouts] = useState<MoverPayout[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { if (!profile?.id || profile.role !== 'mover') return; setLoading(true); try { const [i,p] = await Promise.all([moverApi.getInvoices(), moverApi.getPayouts()]); setInvoices(i); setPayouts(p); } finally { setLoading(false); } }, [profile?.id, profile?.role]);
  useEffect(() => { void load(); }, [load]);
  const released = useMemo(() => payouts.reduce((sum, p) => sum + ((p.final_payment_released_at || p.down_payment_released_at) ? p.net_mover_payable : 0), 0), [payouts]);
  if (loading) return <div className="flex min-h-[400px] items-center justify-center"><RefreshCw className="h-7 w-7 animate-spin text-brand-500" /></div>;
  return <div className="mx-auto max-w-7xl px-2 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="mb-6 flex items-start justify-between gap-4"><div><button type="button" onClick={() => navigate('dashboard')} className="text-sm font-medium text-brand-600 hover:underline dark:text-brand-400">← Back to dashboard</button><h1 className="mt-2 text-2xl font-bold text-gray-900 dark:text-white">Invoices & payouts</h1><p className="mt-1 text-sm text-gray-500 dark:text-gray-400">Review booking invoices and mover payout records.</p></div><button type="button" onClick={() => void load()} className="btn-secondary inline-flex items-center gap-2 text-sm"><RefreshCw className="h-4 w-4" />Refresh</button></div><div className="mb-6 grid gap-4 sm:grid-cols-2"><div className="card p-5"><p className="text-sm text-gray-500 dark:text-gray-400">Invoices</p><p className="mt-1 text-2xl font-bold text-gray-900 dark:text-white">{invoices.length}</p></div><div className="card p-5"><p className="text-sm text-gray-500 dark:text-gray-400">Released mover value</p><p className="mt-1 text-2xl font-bold text-gray-900 dark:text-white">{money(released)}</p></div></div><div className="card overflow-hidden"><div className="border-b border-gray-100 p-5 dark:border-brand-800"><h2 className="font-bold text-gray-900 dark:text-white">Invoice history</h2></div>{invoices.length === 0 ? <div className="p-10 text-center"><FileText className="mx-auto h-9 w-9 text-gray-400" /><p className="mt-3 text-sm text-gray-500 dark:text-gray-400">No invoices yet.</p></div> : <div className="divide-y divide-gray-100 dark:divide-brand-800">{invoices.map((invoice) => <button key={invoice.id} type="button" onClick={() => navigate('mover-booking-detail', invoice.booking_id)} className="flex w-full flex-col gap-2 p-4 text-left hover:bg-gray-50 sm:flex-row sm:items-center sm:justify-between dark:hover:bg-brand-900/30"><div><p className="font-semibold text-gray-900 dark:text-white">{invoice.invoice_number}</p><p className="text-xs text-gray-500 dark:text-gray-400">Booking {invoice.booking_id.slice(0, 8)} · {new Date(invoice.created_at).toLocaleDateString()}</p></div><div className="sm:text-right"><p className="font-semibold text-gray-900 dark:text-white">{money(invoice.mover_net_kes)}</p><span className="text-xs text-gray-500 dark:text-gray-400">{invoice.status}</span></div></button>)}</div>}</div></div>;
}
