# Generated by Django 6.0.8 on 2026-09-03 13:11

import apps.listings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('county', models.TextField(default='')),
                ('location_search', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('property_name', models.TextField(blank=True, null=True)),
                ('property_type', models.TextField(blank=True, null=True)),
                ('price_kes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('listing_type', models.TextField(default='rent')),
                ('deposit_required', models.BooleanField(default=False, null=True)),
                ('deposit_structure', models.TextField(blank=True, default='fixed', null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('size', models.TextField(blank=True, default='', null=True)),
                ('beds', models.IntegerField(default=0, null=True)),
                ('baths', models.IntegerField(default=0, null=True)),
                ('contact_phone', models.TextField(blank=True, default='', null=True)),
                ('contact_email', models.TextField(blank=True, default='', null=True)),
                ('social_links', models.JSONField(default=list)),
                ('booking_enabled', models.BooleanField(default=False)),
                ('payment_enabled', models.BooleanField(default=False)),
                ('is_property_management', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('draft_data', models.JSONField(default=dict)),
                ('approval_status', models.TextField(default='pending_review')),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.TextField(default='pending')),
                ('admin_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_review_note', models.TextField(blank=True, default='', null=True)),
                ('ai_caption', models.TextField(blank=True, null=True)),
                ('ai_caption_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listings',
            },
        ),
        migrations.CreateModel(
            name='ListingPaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('amount_kes', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('status', models.TextField(default='PENDING')),
                ('listing_data', models.JSONField()),
                ('provider', models.TextField(blank=True, null=True)),
                ('provider_reference', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=apps.listings.models._listing_payment_intent_expiry)),
                ('provider_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('provider_currency', models.TextField(blank=True, null=True)),
                ('paypal_order_id', models.TextField(blank=True, null=True)),
                ('paypal_fx_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('listing', models.ForeignKey(blank=True, db_column='listing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='listings.listing')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='listing_payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listing_payment_intents',
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city'], name='idx_listings_city'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at'], name='idx_listings_created_at'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['user'], name='idx_listings_user_id'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_property_management'], name='listing_prop_mgmt_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['user', 'is_draft', '-updated_at'], name='listings_user_draft_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('listing_type__in', ['rent', 'sale'])), name='listings_listing_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_structure__in', ['fixed', 'installments']), ('deposit_structure__isnull', True), _connector='OR'), name='listings_deposit_structure_valid'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('approval_status__in', ['pending_review', 'approved', 'rejected'])), name='listings_approval_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected'])), name='listings_status_valid'),
        ),
        migrations.AddIndex(
            model_name='listingpaymentintent',
            index=models.Index(fields=['listing'], name='listing_pay_intent_listing'),
        ),
        migrations.AddIndex(
            model_name='listingpaymentintent',
            index=models.Index(fields=['user', 'status', '-created_at'], name='listing_pay_intent_user'),
        ),
        migrations.AddIndex(
            model_name='listingpaymentintent',
            index=models.Index(condition=models.Q(('provider_reference__isnull', False)), fields=['provider', 'provider_reference'], name='listing_pay_intent_provider'),
        ),
        migrations.AddConstraint(
            model_name='listingpaymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['landlord', 'real_estate'])), name='listing_payment_intents_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='listingpaymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kes', 1000)), name='listing_payment_intents_amount_1000'),
        ),
        migrations.AddConstraint(
            model_name='listingpaymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'PAID', 'FAILED', 'CANCELLED', 'EXPIRED'])), name='listing_payment_intents_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='listingpaymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference__isnull', False)), fields=('provider_reference',), name='listing_payment_intents_provider_reference_key'),
        ),
        migrations.AddConstraint(
            model_name='listingpaymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('paypal_order_id__isnull', False)), fields=('paypal_order_id',), name='listing_payment_intents_paypal_order_id_key'),
        ),
    ]
