import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0002_profile_signup_verification_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.TextField()),
                ('renter_id', models.UUIDField()),
                ('mover_id', models.UUIDField()),
                ('mover_profile_id', models.UUIDField(blank=True, null=True)),
                ('relocation_date', models.DateField()),
                ('day_of_week', models.TextField()),
                ('pickup_time', models.TimeField()),
                ('pickup_address', models.TextField()),
                ('dropoff_address', models.TextField()),
                ('negotiated_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.TextField(default='pending')),
                ('payment_method', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('rate_per_km_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('base_rate_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={'db_table': 'booking_events'},
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('renter_id', models.UUIDField()),
                ('mover_id', models.UUIDField()),
                ('listing_id', models.UUIDField(blank=True, null=True)),
                ('pickup_address', models.TextField(default='')),
                ('dropoff_address', models.TextField(default='')),
                ('moving_date', models.DateField()),
                ('booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.TextField(default='pending')),
                ('payment_status', models.TextField(default='unpaid')),
                ('payment_method', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('rate_per_km_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('base_rate_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('dropoff_latitude', models.FloatField(blank=True, null=True)),
                ('dropoff_longitude', models.FloatField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('request_expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_start_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancellation_details', models.TextField(blank=True, null=True)),
                ('tracking_number', models.TextField(blank=True, null=True)),
                ('renter_confirmed_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('contact_released_at', models.DateTimeField(blank=True, null=True)),
                ('last_known_latitude', models.FloatField(blank=True, null=True)),
                ('last_known_longitude', models.FloatField(blank=True, null=True)),
                ('last_location_at', models.DateTimeField(blank=True, null=True)),
                ('mover_confirmed_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_status', models.TextField(default='NONE')),
            ],
            options={'db_table': 'bookings'},
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.TextField()),
                ('sender_id', models.UUIDField()),
                ('receiver_id', models.UUIDField()),
                ('content', models.TextField(default='')),
                ('message_type', models.TextField(default='text')),
                ('event_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'db_table': 'chat_messages'},
        ),
        migrations.CreateModel(
            name='MoverScheduleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mover_id', models.UUIDField()),
                ('booking_id', models.UUIDField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.TextField(default='CONFIRMED')),
                ('title', models.TextField(default='Moving service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'mover_schedule_events'},
        ),
        migrations.CreateModel(
            name='MovingCancellationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField()),
                ('cancelled_by', models.UUIDField()),
                ('reason_code', models.TextField()),
                ('reason_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'db_table': 'moving_cancellation_events'},
        ),
        migrations.CreateModel(
            name='MovingDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField()),
                ('opened_by', models.UUIDField()),
                ('reason_code', models.TextField()),
                ('description', models.TextField()),
                ('status', models.TextField(default='OPEN')),
                ('resolution_code', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_by', models.UUIDField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'moving_disputes'},
        ),
        migrations.CreateModel(
            name='MovingTrackingPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField()),
                ('mover_id', models.UUIDField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('speed_kph', models.FloatField(blank=True, null=True)),
                ('heading_degrees', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'db_table': 'moving_tracking_points'},
        ),
        migrations.CreateModel(
            name='MovingInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField()),
                ('invoice_number', models.TextField()),
                ('renter_id', models.UUIDField()),
                ('mover_id', models.UUIDField()),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=14)),
                ('platform_fee_kes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mover_net_kes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.TextField(default='KES')),
                ('status', models.TextField(default='ISSUED')),
                ('payment_provider', models.TextField(blank=True, null=True)),
                ('provider_reference', models.TextField(blank=True, null=True)),
                ('provider_transaction_id', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('mover_name_snapshot', models.TextField(default='')),
                ('mover_phone_snapshot', models.TextField(blank=True, null=True)),
                ('vehicle_type_snapshot', models.TextField(blank=True, null=True)),
                ('number_plate_snapshot', models.TextField(blank=True, null=True)),
                ('mover_profile_photo_snapshot', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'moving_invoices'},
        ),
        migrations.CreateModel(
            name='MovingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField()),
                ('invoice_id', models.UUIDField()),
                ('payer_id', models.UUIDField()),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=14)),
                ('provider', models.TextField()),
                ('status', models.TextField(default='PENDING')),
                ('provider_reference', models.TextField(blank=True, null=True)),
                ('provider_transaction_id', models.TextField(blank=True, null=True)),
                ('mpesa_receipt', models.TextField(blank=True, null=True)),
                ('paypal_order_id', models.TextField(blank=True, null=True)),
                ('provider_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('provider_currency', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'moving_payments'},
        ),
        migrations.CreateModel(
            name='MoverPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField()),
                ('mover_id', models.UUIDField()),
                ('mover_name', models.TextField(default='')),
                ('national_id', models.TextField(default='')),
                ('payment_channel', models.TextField()),
                ('renter_payment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('platform_deduction', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_mover_payable', models.DecimalField(decimal_places=2, max_digits=14)),
                ('down_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('final_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('down_payment_status', models.TextField(default='held')),
                ('final_payment_status', models.TextField(default='held')),
                ('job_started_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('down_payment_released_at', models.DateTimeField(blank=True, null=True)),
                ('final_payment_released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_provider', models.TextField(blank=True, null=True)),
                ('payout_provider_reference', models.TextField(blank=True, null=True)),
                ('payout_provider_transaction_id', models.TextField(blank=True, null=True)),
                ('payout_failure_reason', models.TextField(blank=True, null=True)),
                ('payout_requested_at', models.DateTimeField(blank=True, null=True)),
                ('payout_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={'db_table': 'mover_payouts'},
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'in_progress', 'completed', 'cancelled'])), name='bookings_status_check'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('payment_status__in', ['unpaid', 'paid', 'refunded'])), name='bookings_payment_status_check'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('dispute_status__in', ['NONE', 'OPEN', 'RESOLVED'])), name='bookings_dispute_status_check'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(('message_type__in', ['text', 'image', 'booking_request', 'booking_response', 'schedule_proposed', 'schedule_confirmed', 'event_request', 'event_confirmed', 'event_declined', 'system'])), name='chat_messages_message_type_check'),
        ),
        migrations.AddConstraint(
            model_name='moverscheduleevent',
            constraint=models.CheckConstraint(condition=models.Q(ends_at__gt=models.F('starts_at')), name='mover_schedule_events_check'),
        ),
        migrations.AddConstraint(
            model_name='moverscheduleevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['TENTATIVE', 'CONFIRMED', 'CANCELLED'])), name='mover_schedule_events_status_check'),
        ),
        migrations.AddConstraint(
            model_name='moverscheduleevent',
            constraint=models.UniqueConstraint(fields=('booking_id',), name='mover_schedule_events_booking_id_key'),
        ),
        migrations.AddConstraint(
            model_name='movingcancellationevent',
            constraint=models.CheckConstraint(condition=models.Q(('reason_code__in', ['MOVER_DID_NOT_CONFIRM', 'MOVER_TAKING_TOO_LONG', 'CHANGED_MIND', 'OTHER', 'RENTER_CANCELLED', 'MOVER_CANCELLED', 'MOVER_UNAVAILABLE'])), name='moving_cancellation_events_reason_code_check'),
        ),
        migrations.AddConstraint(
            model_name='movingdispute',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'RESOLVED'])), name='moving_disputes_status_check'),
        ),
        migrations.AddConstraint(
            model_name='movingdispute',
            constraint=models.CheckConstraint(condition=models.Q(resolution_code__isnull=True) | models.Q(('resolution_code__in', ['RELEASE_TO_MOVER', 'REFUND_RENTER', 'PARTIAL_REFUND', 'NO_REFUND'])), name='moving_disputes_resolution_check'),
        ),
        migrations.AddConstraint(
            model_name='movingtrackingpoint',
            constraint=models.CheckConstraint(condition=models.Q(latitude__gte=-90) & models.Q(latitude__lte=90), name='moving_tracking_points_latitude_check'),
        ),
        migrations.AddConstraint(
            model_name='movingtrackingpoint',
            constraint=models.CheckConstraint(condition=models.Q(longitude__gte=-180) & models.Q(longitude__lte=180), name='moving_tracking_points_longitude_check'),
        ),
        migrations.AddConstraint(
            model_name='movinginvoice',
            constraint=models.CheckConstraint(condition=models.Q(amount_kes__gte=0), name='moving_invoices_amount_kes_check'),
        ),
        migrations.AddConstraint(
            model_name='movinginvoice',
            constraint=models.CheckConstraint(condition=models.Q(platform_fee_kes__gte=0), name='moving_invoices_platform_fee_kes_check'),
        ),
        migrations.AddConstraint(
            model_name='movinginvoice',
            constraint=models.CheckConstraint(condition=models.Q(mover_net_kes__gte=0), name='moving_invoices_mover_net_kes_check'),
        ),
        migrations.AddConstraint(
            model_name='movinginvoice',
            constraint=models.CheckConstraint(condition=models.Q(currency='KES'), name='moving_invoices_currency_check'),
        ),
        migrations.AddConstraint(
            model_name='movinginvoice',
            constraint=models.CheckConstraint(condition=models.Q(payment_provider__isnull=True) | models.Q(('payment_provider__in', ['MPESA', 'PAYPAL'])), name='moving_invoices_payment_provider_check'),
        ),
        migrations.AddConstraint(
            model_name='movinginvoice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ISSUED', 'PAID', 'HELD', 'RELEASED', 'REFUNDED', 'CANCELLED'])), name='moving_invoices_status_check'),
        ),
        migrations.AddConstraint(
            model_name='movinginvoice',
            constraint=models.UniqueConstraint(fields=('booking_id',), name='moving_invoices_booking_id_key'),
        ),
        migrations.AddConstraint(
            model_name='movinginvoice',
            constraint=models.UniqueConstraint(fields=('invoice_number',), name='moving_invoices_invoice_number_key'),
        ),
        migrations.AddConstraint(
            model_name='movingpayment',
            constraint=models.CheckConstraint(condition=models.Q(amount_kes__gt=0), name='moving_payments_amount_kes_check'),
        ),
        migrations.AddConstraint(
            model_name='movingpayment',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ['MPESA', 'PAYPAL'])), name='moving_payments_provider_check'),
        ),
        migrations.AddConstraint(
            model_name='movingpayment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'PROCESSING', 'PAID', 'HELD', 'RELEASED', 'FAILED', 'REFUNDED', 'CANCELLED'])), name='moving_payments_status_check'),
        ),
        migrations.AddConstraint(
            model_name='moverpayout',
            constraint=models.CheckConstraint(condition=models.Q(renter_payment__gte=0), name='mover_payouts_renter_payment_check'),
        ),
        migrations.AddConstraint(
            model_name='moverpayout',
            constraint=models.CheckConstraint(condition=models.Q(platform_deduction__gte=0), name='mover_payouts_platform_deduction_check'),
        ),
        migrations.AddConstraint(
            model_name='moverpayout',
            constraint=models.CheckConstraint(condition=models.Q(net_mover_payable__gte=0), name='mover_payouts_net_mover_payable_check'),
        ),
        migrations.AddConstraint(
            model_name='moverpayout',
            constraint=models.CheckConstraint(condition=models.Q(down_payment_amount__gte=0), name='mover_payouts_down_payment_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='moverpayout',
            constraint=models.CheckConstraint(condition=models.Q(final_payment_amount__gte=0), name='mover_payouts_final_payment_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='moverpayout',
            constraint=models.CheckConstraint(condition=models.Q(('payment_channel__in', ['mpesa_send_money', 'mpesa_paybill', 'mpesa_lipa_na_mpesa', 'airtel_money'])), name='mover_payouts_payment_channel_check'),
        ),
        migrations.AddConstraint(
            model_name='moverpayout',
            constraint=models.CheckConstraint(condition=models.Q(('down_payment_status__in', ['held', 'released'])), name='mover_payouts_down_payment_status_check'),
        ),
        migrations.AddConstraint(
            model_name='moverpayout',
            constraint=models.CheckConstraint(condition=models.Q(('final_payment_status__in', ['held', 'processing', 'failed', 'released'])), name='mover_payouts_final_payment_status_check'),
        ),
        migrations.AddConstraint(
            model_name='moverpayout',
            constraint=models.UniqueConstraint(fields=('booking_id',), name='mover_payouts_booking_id_key'),
        ),
    ]
