# Generated by Django 6.0.8 on 2026-09-03 23:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mover_application_schedule_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='ai_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moverapplication',
            name='working_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True),
        ),
    ]
