import uuid
from django.db import models

class BookingEvent(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); conversation_id=models.TextField(); renter_id=models.UUIDField(); mover_id=models.UUIDField(); mover_profile_id=models.UUIDField(null=True,blank=True); relocation_date=models.DateField(); day_of_week=models.TextField(); pickup_time=models.TimeField(); pickup_address=models.TextField(); dropoff_address=models.TextField(); negotiated_price=models.DecimalField(max_digits=14,decimal_places=2,default=0); commission_amount=models.DecimalField(max_digits=14,decimal_places=2,default=0); total_amount=models.DecimalField(max_digits=14,decimal_places=2,default=0); status=models.TextField(default='pending'); payment_method=models.TextField(blank=True,default=''); created_at=models.DateTimeField(auto_now_add=True); confirmed_at=models.DateTimeField(null=True,blank=True); paid_at=models.DateTimeField(null=True,blank=True); distance_km=models.DecimalField(max_digits=14,decimal_places=4,null=True,blank=True); rate_per_km_kes=models.DecimalField(max_digits=14,decimal_places=2,null=True,blank=True); base_rate_kes=models.DecimalField(max_digits=14,decimal_places=2,null=True,blank=True)
    class Meta: db_table='booking_events'

class Booking(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); renter_id=models.UUIDField(); mover_id=models.UUIDField(); listing_id=models.UUIDField(null=True,blank=True); pickup_address=models.TextField(default=''); dropoff_address=models.TextField(default=''); moving_date=models.DateField(); booking_amount=models.DecimalField(max_digits=14,decimal_places=2,default=0); commission_amount=models.DecimalField(max_digits=14,decimal_places=2,default=0); total_amount=models.DecimalField(max_digits=14,decimal_places=2,default=0); status=models.TextField(default='pending'); payment_status=models.TextField(default='unpaid'); payment_method=models.TextField(blank=True,default=''); created_at=models.DateTimeField(null=True,blank=True); updated_at=models.DateTimeField(null=True,blank=True); distance_km=models.DecimalField(max_digits=14,decimal_places=4,null=True,blank=True); rate_per_km_kes=models.DecimalField(max_digits=14,decimal_places=2,null=True,blank=True); base_rate_kes=models.DecimalField(max_digits=14,decimal_places=2,null=True,blank=True); pickup_latitude=models.FloatField(null=True,blank=True); pickup_longitude=models.FloatField(null=True,blank=True); dropoff_latitude=models.FloatField(null=True,blank=True); dropoff_longitude=models.FloatField(null=True,blank=True); requested_at=models.DateTimeField(null=True,blank=True); request_expires_at=models.DateTimeField(null=True,blank=True); confirmed_at=models.DateTimeField(null=True,blank=True); scheduled_start_at=models.DateTimeField(null=True,blank=True); scheduled_end_at=models.DateTimeField(null=True,blank=True); started_at=models.DateTimeField(null=True,blank=True); completed_at=models.DateTimeField(null=True,blank=True); cancelled_at=models.DateTimeField(null=True,blank=True); cancellation_reason=models.TextField(null=True,blank=True); cancellation_details=models.TextField(null=True,blank=True); tracking_number=models.TextField(null=True,blank=True); renter_confirmed_delivery_at=models.DateTimeField(null=True,blank=True); contact_released_at=models.DateTimeField(null=True,blank=True); last_known_latitude=models.FloatField(null=True,blank=True); last_known_longitude=models.FloatField(null=True,blank=True); last_location_at=models.DateTimeField(null=True,blank=True); mover_confirmed_delivery_at=models.DateTimeField(null=True,blank=True); dispute_status=models.TextField(default='NONE')
    class Meta: db_table='bookings'

class ChatMessage(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); conversation_id=models.TextField(); sender_id=models.UUIDField(); receiver_id=models.UUIDField(); content=models.TextField(default=''); message_type=models.TextField(default='text'); event_data=models.JSONField(null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True)
    class Meta: db_table='chat_messages'

class MoverScheduleEvent(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); mover_id=models.UUIDField(); booking_id=models.UUIDField(); starts_at=models.DateTimeField(); ends_at=models.DateTimeField(); status=models.TextField(default='CONFIRMED'); title=models.TextField(default='Moving service'); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True)
    class Meta: db_table='mover_schedule_events'

class MovingCancellationEvent(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); booking_id=models.UUIDField(); cancelled_by=models.UUIDField(); reason_code=models.TextField(); reason_text=models.TextField(null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True)
    class Meta: db_table='moving_cancellation_events'

class MovingDispute(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); booking_id=models.UUIDField(); opened_by=models.UUIDField(); reason_code=models.TextField(); description=models.TextField(); status=models.TextField(default='OPEN'); resolution_code=models.TextField(null=True,blank=True); resolution_notes=models.TextField(null=True,blank=True); resolved_by=models.UUIDField(null=True,blank=True); opened_at=models.DateTimeField(auto_now_add=True); resolved_at=models.DateTimeField(null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True)
    class Meta: db_table='moving_disputes'

class MovingTrackingPoint(models.Model):
    id=models.BigAutoField(primary_key=True); booking_id=models.UUIDField(); mover_id=models.UUIDField(); latitude=models.FloatField(); longitude=models.FloatField(); accuracy_meters=models.FloatField(null=True,blank=True); speed_kph=models.FloatField(null=True,blank=True); heading_degrees=models.FloatField(null=True,blank=True); recorded_at=models.DateTimeField(auto_now_add=True)
    class Meta: db_table='moving_tracking_points'

class MovingInvoice(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); booking_id=models.UUIDField(); invoice_number=models.TextField(); renter_id=models.UUIDField(); mover_id=models.UUIDField(); amount_kes=models.DecimalField(max_digits=14,decimal_places=2); platform_fee_kes=models.DecimalField(max_digits=14,decimal_places=2,default=0); mover_net_kes=models.DecimalField(max_digits=14,decimal_places=2,default=0); currency=models.TextField(default='KES'); status=models.TextField(default='ISSUED'); payment_provider=models.TextField(null=True,blank=True); provider_reference=models.TextField(null=True,blank=True); provider_transaction_id=models.TextField(null=True,blank=True); paid_at=models.DateTimeField(null=True,blank=True); released_at=models.DateTimeField(null=True,blank=True); mover_name_snapshot=models.TextField(default=''); mover_phone_snapshot=models.TextField(null=True,blank=True); vehicle_type_snapshot=models.TextField(null=True,blank=True); number_plate_snapshot=models.TextField(null=True,blank=True); mover_profile_photo_snapshot=models.TextField(null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True)
    class Meta: db_table='moving_invoices'

class MovingPayment(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); booking_id=models.UUIDField(); invoice_id=models.UUIDField(); payer_id=models.UUIDField(); amount_kes=models.DecimalField(max_digits=14,decimal_places=2); provider=models.TextField(); status=models.TextField(default='PENDING'); provider_reference=models.TextField(null=True,blank=True); provider_transaction_id=models.TextField(null=True,blank=True); mpesa_receipt=models.TextField(null=True,blank=True); paypal_order_id=models.TextField(null=True,blank=True); provider_amount=models.DecimalField(max_digits=14,decimal_places=2,null=True,blank=True); provider_currency=models.TextField(null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True); paid_at=models.DateTimeField(null=True,blank=True); released_at=models.DateTimeField(null=True,blank=True); updated_at=models.DateTimeField(auto_now=True)
    class Meta: db_table='moving_payments'

class MoverPayout(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); booking_id=models.UUIDField(); mover_id=models.UUIDField(); mover_name=models.TextField(default=''); national_id=models.TextField(default=''); payment_channel=models.TextField(); renter_payment=models.DecimalField(max_digits=14,decimal_places=2); platform_deduction=models.DecimalField(max_digits=14,decimal_places=2); net_mover_payable=models.DecimalField(max_digits=14,decimal_places=2); down_payment_amount=models.DecimalField(max_digits=14,decimal_places=2,default=0); final_payment_amount=models.DecimalField(max_digits=14,decimal_places=2,default=0); down_payment_status=models.TextField(default='held'); final_payment_status=models.TextField(default='held'); job_started_at=models.DateTimeField(null=True,blank=True); delivery_confirmed_at=models.DateTimeField(null=True,blank=True); down_payment_released_at=models.DateTimeField(null=True,blank=True); final_payment_released_at=models.DateTimeField(null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True); payout_provider=models.TextField(null=True,blank=True); payout_provider_reference=models.TextField(null=True,blank=True); payout_provider_transaction_id=models.TextField(null=True,blank=True); payout_failure_reason=models.TextField(null=True,blank=True); payout_requested_at=models.DateTimeField(null=True,blank=True); payout_completed_at=models.DateTimeField(null=True,blank=True)
    class Meta: db_table='mover_payouts'
