from io import BytesIO

from django.http import FileResponse
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.accounts.authorization import can_manage_listings
from apps.accounts.models import Profile

from .domain_rent import RentInvoice


class RentInvoiceDownloadView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, invoice_id):
        invoice = RentInvoice.objects.filter(pk=invoice_id).first()
        if invoice is None:
            return Response({"detail": "Invoice not found."}, status=404)
        is_landlord = can_manage_listings(request.user) and str(invoice.landlord_id) == str(request.user.id)
        is_renter = str(invoice.renter_user_id) == str(request.user.id)
        if not (is_landlord or is_renter):
            return Response({"detail": "You are not authorized to download this invoice."}, status=403)

        landlord = Profile.objects.filter(pk=invoice.landlord_id).only("full_name", "email", "phone").first()
        renter = Profile.objects.filter(pk=invoice.renter_user_id).only("full_name", "email", "phone").first()
        destination = invoice.payment_destination_snapshot or {}

        buffer = BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4
        y = height - 60
        pdf.setTitle(invoice.invoice_number)
        pdf.setFont("Helvetica-Bold", 18)
        pdf.drawString(50, y, "SakaCrib Rent Invoice")
        y -= 32
        pdf.setFont("Helvetica", 10)
        lines = [
            ("Invoice", invoice.invoice_number),
            ("Status", invoice.status),
            ("Property / Unit", f"{invoice.listing_id} / {invoice.unit_id}"),
            ("Billing period", f"{invoice.billing_period_start} to {invoice.billing_period_end}"),
            ("Due date", str(invoice.due_date)),
            ("Amount", f"{invoice.currency} {invoice.amount_kes:,.2f}"),
            ("Landlord", f"{landlord.full_name if landlord else invoice.landlord_id}"),
            ("Renter", f"{renter.full_name if renter else invoice.renter_user_id}"),
        ]
        for label, value in lines:
            pdf.setFont("Helvetica-Bold", 10)
            pdf.drawString(50, y, f"{label}:")
            pdf.setFont("Helvetica", 10)
            pdf.drawString(170, y, str(value))
            y -= 20
        if destination:
            y -= 8
            pdf.setFont("Helvetica-Bold", 11)
            pdf.drawString(50, y, "Payment destination")
            y -= 18
            pdf.setFont("Helvetica", 9)
            for key in ("provider", "mpesa_method", "display_name", "paybill_number", "paybill_account", "till_number", "paypal_email"):
                value = destination.get(key)
                if value:
                    pdf.drawString(60, y, f"{key.replace('_', ' ').title()}: {value}")
                    y -= 16
        if invoice.transaction_reference:
            y -= 8
            pdf.setFont("Helvetica-Bold", 10)
            pdf.drawString(50, y, f"Transaction reference: {invoice.transaction_reference}")
            y -= 18
        if invoice.paid_at:
            pdf.drawString(50, y, f"Paid at: {invoice.paid_at}")
            y -= 18
        pdf.setFont("Helvetica-Oblique", 8)
        pdf.drawString(50, 45, "Generated by SakaCrib. Payment status reflects the recorded Django rent workflow.")
        pdf.showPage()
        pdf.save()
        buffer.seek(0)
        return FileResponse(buffer, as_attachment=True, filename=f"{invoice.invoice_number}.pdf", content_type="application/pdf")
