# Generated by Django 6.0.8 on 2026-09-03 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('max_units_per_listing', models.IntegerField(blank=True, null=True)),
                ('monthly_price_kes', models.DecimalField(decimal_places=2, max_digits=14)),
                ('annual_price_kes', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField()),
                ('max_listings', models.IntegerField(blank=True, null=True)),
                ('audience', models.TextField(default='LANDLORD')),
                ('paypal_product_id', models.TextField(blank=True, null=True)),
                ('paypal_monthly_plan_id', models.TextField(blank=True, null=True)),
                ('paypal_annual_plan_id', models.TextField(blank=True, null=True)),
                ('paypal_monthly_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('paypal_annual_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('paypal_fx_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('paypal_fx_rate_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='LandlordSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('landlord_id', models.UUIDField()),
                ('plan_id', models.UUIDField()),
                ('billing_cycle', models.TextField(default='MONTHLY')),
                ('status', models.TextField(default='PENDING_PAYMENT')),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('grace_period_end', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('paypal_subscription_id', models.TextField(blank=True, null=True)),
                ('paypal_plan_id', models.TextField(blank=True, null=True)),
                ('paypal_status', models.TextField(blank=True, null=True)),
                ('next_billing_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('billing_amount_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('billing_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('billing_exchange_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('billing_exchange_rate_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'landlord_subscriptions',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING_PAYMENT')), fields=('landlord_id',), name='landlord_sub_pending_uidx'), models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'GRACE_PERIOD'])), fields=('landlord_id',), name='landlord_sub_current_uidx'), models.UniqueConstraint(condition=models.Q(('paypal_subscription_id__isnull', False)), fields=('paypal_subscription_id',), name='landlord_sub_paypal_uidx')],
            },
        ),
        migrations.CreateModel(
            name='RealEstateSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('real_estate_id', models.UUIDField()),
                ('plan_id', models.UUIDField()),
                ('billing_cycle', models.TextField(default='MONTHLY')),
                ('status', models.TextField(default='PENDING_PAYMENT')),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('grace_period_end', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('paypal_subscription_id', models.TextField(blank=True, null=True)),
                ('paypal_plan_id', models.TextField(blank=True, null=True)),
                ('paypal_status', models.TextField(blank=True, null=True)),
                ('next_billing_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('billing_amount_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('billing_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('billing_exchange_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('billing_exchange_rate_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'real_estate_subscriptions',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING_PAYMENT')), fields=('real_estate_id',), name='realestate_sub_pending_uidx'), models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'GRACE_PERIOD'])), fields=('real_estate_id',), name='realestate_sub_current_uidx'), models.UniqueConstraint(condition=models.Q(('paypal_subscription_id__isnull', False)), fields=('paypal_subscription_id',), name='realestate_sub_paypal_uidx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_id', models.UUIDField(blank=True, null=True)),
                ('listing_id', models.UUIDField()),
                ('status', models.TextField(default='ACTIVE')),
                ('activated_at', models.DateTimeField()),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('real_estate_subscription_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription_listings',
                'constraints': [models.UniqueConstraint(condition=models.Q(('subscription_id__isnull', False)), fields=('subscription_id', 'listing_id'), name='subscription_listing_landlord_uidx'), models.UniqueConstraint(condition=models.Q(('real_estate_subscription_id__isnull', False)), fields=('real_estate_subscription_id', 'listing_id'), name='subscription_listing_re_uidx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mpesa_receipt', models.TextField(blank=True, null=True)),
                ('checkout_request_id', models.TextField(blank=True, null=True)),
                ('merchant_request_id', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='PENDING')),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_provider', models.TextField(default='MPESA')),
                ('provider_reference', models.TextField(blank=True, null=True)),
                ('provider_transaction_id', models.TextField(blank=True, null=True)),
                ('payment_method', models.TextField(blank=True, null=True)),
                ('landlord_subscription_id', models.UUIDField(blank=True, null=True)),
                ('real_estate_subscription_id', models.UUIDField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('exchange_rate_source', models.TextField(blank=True, null=True)),
                ('exchange_rate_timestamp', models.DateTimeField(blank=True, null=True)),
                ('paypal_subscription_id', models.TextField(blank=True, null=True)),
                ('billing_period_start', models.DateTimeField(blank=True, null=True)),
                ('billing_period_end', models.DateTimeField(blank=True, null=True)),
                ('webhook_event_id', models.TextField(blank=True, null=True)),
                ('pricing_snapshot_source', models.TextField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, db_column='listing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_invoices', to='listings.listing')),
            ],
            options={
                'db_table': 'subscription_invoices',
                'constraints': [models.UniqueConstraint(condition=models.Q(('webhook_event_id__isnull', False)), fields=('webhook_event_id',), name='subscription_invoices_webhook_event_uidx'), models.UniqueConstraint(condition=models.Q(('checkout_request_id__isnull', False)), fields=('checkout_request_id',), name='subscription_invoice_checkout_uidx'), models.UniqueConstraint(condition=models.Q(('provider_reference__isnull', False)), fields=('provider_reference',), name='subscription_invoice_provider_ref_uidx'), models.UniqueConstraint(condition=models.Q(('paypal_subscription_id__isnull', False)), fields=('paypal_subscription_id',), name='subscription_invoice_paypal_sub_uidx')],
            },
        ),
    ]
