import { protectedGet, protectedPost } from '@/lib/djangoApi';

export type PMSBillingCycle = 'MONTHLY' | 'ANNUAL';
export type PMSSubscriptionStatus = 'PENDING_PAYMENT' | 'ACTIVE' | 'GRACE_PERIOD' | 'EXPIRED' | 'CANCELLED';
export type PMSPlanName = 'STARTER' | 'GROWTH' | 'PRO' | 'ENTERPRISE';

export interface PMSSubscription { id: string; subscription_id: string; landlord_id: string; plan_id: string; plan_name: PMSPlanName | string; max_listings: number | null; billing_cycle: PMSBillingCycle; status: PMSSubscriptionStatus; current_period_start: string; current_period_end: string; grace_period_end: string | null; auto_renew: boolean; created_at?: string; updated_at?: string; }
export interface PMSPlan { id: string; name: PMSPlanName | string; audience: 'LANDLORD' | 'REAL_ESTATE' | string; max_listings: number | null; max_units_per_listing: number | null; monthly_price_kes: number; annual_price_kes: number; }
export interface PMSCapacity { listings_used: number; max_listings: number | null; listings_remaining: number | null; max_units_per_listing: number | null; }
export interface PMSListing { subscription_listing_id: string; subscription_id: string; listing_id: string; listing_title: string; listing_city: string; listing_price_kes: number; status: 'ACTIVE' | 'INACTIVE' | string; activated_at: string; }
export interface PMSAvailableListing { listing_id: string; title: string; city: string; price_kes: number; created_at: string; }
export interface PMSUnit { unit_id: string; listing_id: string; listing_title: string; unit_number: string; unit_type: string | null; rent: number | null; beds: number | null; baths: number | null; availability: string | null; renter_name: string | null; renter_assoc_id: string | null; renter_phone: string | null; renter_email: string | null; lease_start: string | null; lease_end: string | null; assoc_status: string | null; }
export interface LandlordListing { id: string; user_id: string; title: string; description: string; city: string; county: string; location_search: string | null; latitude: number | null; longitude: number | null; property_name: string | null; property_type: string | null; price_kes: number | null; listing_type: string | null; deposit_required: boolean | null; deposit_structure: string | null; deposit_amount: number | null; size: string | null; beds: number | null; baths: number | null; contact_phone: string | null; contact_email: string | null; social_links: Record<string, unknown> | null; booking_enabled: boolean; payment_enabled: boolean; is_property_management: boolean; is_paid: boolean; is_published: boolean; approval_status: string | null; is_approved: boolean; admin_reviewed_at: string | null; admin_review_note: string | null; status: string | null; created_at: string; updated_at: string; cover_photo_url?: string | null; }
export interface ListingPayment { id: string; listing_id: string; user_id: string; amount_kes: number; mpesa_receipt: string | null; checkout_request_id: string | null; merchant_request_id: string | null; phone_number: string | null; status: string; result_code: number | null; result_description: string | null; payment_provider: string | null; payment_method: string | null; provider_reference: string | null; provider_amount: number | null; provider_currency: string | null; paypal_order_id: string | null; paypal_fx_rate: number | null; created_at: string; paid_at: string | null; }
export interface LandlordPaymentMethod { id: string; provider: string; mpesa_method: string | null; display_name: string | null; paybill_number: string | null; paybill_account: string | null; till_number: string | null; paypal_email: string | null; is_default: boolean; is_active: boolean; created_at: string; updated_at: string; }
export interface LandlordListingEntitlement { landlord_id: string; authorized_landlord: boolean; role?: string; landlord_application_status?: string | null; verification_status?: string | null; free_limit?: number; free_listings_used?: number; free_listings_remaining?: number; subscription_id?: string | null; plan_id?: string | null; subscription_plan?: string | null; subscription_status?: string | null; subscription_limit?: number | null; max_units_per_listing?: number | null; subscription_listings_used?: number; subscription_listings_remaining?: number | null; individual_paid_listings?: number; individual_listing_price_kes?: number; can_start_listing?: boolean; can_create?: boolean; requires_subscription?: boolean; requires_individual_payment?: boolean; pms_access?: boolean; upgrade_available?: boolean; upgrade_target?: string | null; reason?: string; }
export interface PMSSubscriptionAccess { authenticated: boolean; is_landlord: boolean; role?: string; has_subscription: boolean; subscription_id?: string; plan_id?: string; plan_name?: string; max_units_per_listing?: number | null; billing_cycle?: PMSBillingCycle; status: PMSSubscriptionStatus | string; current_period_start?: string; current_period_end?: string; grace_period_end?: string | null; days_remaining?: number; grace_days_remaining?: number; auto_renew?: boolean; can_manage: boolean; can_view_properties: boolean; can_view_payment_history: boolean; can_create_units: boolean; can_send_sms: boolean; can_reconcile_rent: boolean; }
export interface PMSNotification { id: string; source: 'USER' | 'PMS'; notification_type: string; title: string; message: string; action_type?: string | null; action_payload?: Record<string, unknown> | null; action_required?: boolean; read: boolean; created_at: string; read_at: string | null; }
export interface PMSSubscriptionInvoice { id: string; amount_kes: number; amount_usd: number | null; currency: string | null; mpesa_receipt: string | null; checkout_request_id: string | null; merchant_request_id: string | null; phone_number: string | null; status: string; result_code: number | null; result_description: string | null; payment_provider: string | null; payment_method: string | null; provider_reference: string | null; provider_transaction_id: string | null; billing_period_start: string | null; billing_period_end: string | null; created_at: string; paid_at: string | null; }
export interface LandlordRentInvoice { id: string; invoice_number: string; landlord_id: string; renter_user_id: string | null; renter_assoc_id: string | null; listing_id: string; unit_id: string; billing_period_start: string; billing_period_end: string; due_date: string; amount_kes: number; currency: string; status: string; payment_method_id: string | null; payment_destination_snapshot: Record<string, unknown> | null; paid_at: string | null; confirmed_by: string | null; confirmed_at: string | null; created_at: string; updated_at: string; }
export interface LandlordRentPayment { id: string; renter_assoc_id: string; unit_id: string; landlord_id: string; amount_kes: number; period_year: number; period_month: number; status: string; mpesa_receipt: string | null; checkout_request_id: string | null; paid_at: string | null; payment_provider: string | null; payment_method: string | null; provider_reference: string | null; provider_amount: number | null; provider_currency: string | null; paypal_order_id: string | null; paypal_fx_rate: number | null; merchant_request_id: string | null; phone_number: string | null; result_code: number | null; result_description: string | null; payment_method_id: string | null; created_at?: string; updated_at?: string; }
export interface RentPaymentSubmission { id: string; invoice_id: string; renter_user_id: string | null; landlord_id: string; renter_assoc_id: string; unit_id: string; transaction_reference: string; status: string; submitted_at: string; confirmed_by: string | null; confirmed_at: string | null; rejection_reason: string | null; created_at: string; updated_at: string; }
export interface LandlordRentSummary { invoice_count: number; total_invoiced_kes: number; paid_invoice_count: number; paid_amount_kes: number; pending_invoice_count: number; pending_amount_kes: number; overdue_invoice_count: number; overdue_amount_kes: number; pending_submission_count: number; payment_count: number; total_payments_kes: number; }
export interface LandlordListingSummary { total: number; published: number; unpublished: number; approved: number; pending_approval: number; rejected: number; paid: number; unpaid: number; pms_managed: number; }
export interface PMSDashboardData { subscription: PMSSubscription | null; subscriptionAccess: PMSSubscriptionAccess; entitlement: LandlordListingEntitlement; capacity: PMSCapacity; listings: LandlordListing[]; listingSummary: LandlordListingSummary; pmsListings: PMSListing[]; availableListings: PMSAvailableListing[]; units: PMSUnit[]; plans: PMSPlan[]; paymentMethods: LandlordPaymentMethod[]; listingPayments: ListingPayment[]; subscriptionInvoices: PMSSubscriptionInvoice[]; notifications: PMSNotification[]; rentInvoices: LandlordRentInvoice[]; rentPayments: LandlordRentPayment[]; pendingRentSubmissions: RentPaymentSubmission[]; rentSummary: LandlordRentSummary; }
export interface CreateLandlordListingInput { title: string; description: string; city: string; county: string; location_search?: string | null; latitude?: number | null; longitude?: number | null; property_name?: string | null; property_type?: string | null; price_kes?: number | null; listing_type?: string | null; deposit_required?: boolean | null; deposit_structure?: string | null; deposit_amount?: number | null; size?: string | null; beds?: number | null; baths?: number | null; contact_phone?: string | null; contact_email?: string | null; social_links?: Record<string, unknown> | null; booking_enabled?: boolean; payment_enabled?: boolean; is_property_management?: boolean; }
export interface PMSPaymentRequest { plan_id: string; billing_cycle: PMSBillingCycle; }
export interface PMSPaymentResponse { success: boolean; message?: string; error?: string; invoice_id?: string; subscription_id?: string; plan?: string; billing_cycle?: PMSBillingCycle; amount_kes?: number; checkout_request_id?: string; merchant_request_id?: string | null; customer_message?: string; }

const dashboard = () => protectedGet<PMSDashboardData>('/api/core/pms/dashboard/');
const action = (body: Record<string, unknown>) => protectedPost<{ success: boolean }>('/api/core/pms/action/', body);

export async function getMyPMSSubscription(): Promise<PMSSubscription | null> {
  const row = await protectedGet<Record<string, unknown>>('/api/subscriptions/me/');
  if (!row?.subscription_id) return null;
  return { id: String(row.subscription_id), subscription_id: String(row.subscription_id), landlord_id: '', plan_id: row.plan_id ? String(row.plan_id) : '', plan_name: String(row.plan_name ?? ''), max_listings: row.max_listings == null ? null : Number(row.max_listings), billing_cycle: row.billing_cycle as PMSBillingCycle, status: String(row.subscription_status) as PMSSubscriptionStatus, current_period_start: String(row.current_period_start), current_period_end: String(row.current_period_end), grace_period_end: row.grace_period_end ? String(row.grace_period_end) : null, auto_renew: Boolean(row.auto_renew) };
}
export const getMyPMSSubscriptionAccess = () => protectedGet<PMSSubscriptionAccess>('/api/subscriptions/me/access/');
export async function getLandlordListingEntitlement(): Promise<LandlordListingEntitlement> { const raw = await protectedGet<Record<string, any>>('/api/listings/entitlement/'); return { ...raw, landlord_id: '', authorized_landlord: Boolean(raw.authorized), pms_access: Boolean(raw.subscription_id), individual_listing_price_kes: raw.individual_listing_price_kes == null ? undefined : Number(raw.individual_listing_price_kes) }; }
export function computePMSCapacity(listingsUsed: number, subscription: PMSSubscription | null, subscriptionAccess?: PMSSubscriptionAccess | null): PMSCapacity { const maxListings = subscription?.max_listings ?? null; return { listings_used: listingsUsed, max_listings: maxListings, listings_remaining: maxListings == null ? null : Math.max(0, maxListings - listingsUsed), max_units_per_listing: subscriptionAccess?.max_units_per_listing ?? null }; }
export async function getMyPMSUnitCount(subscriptionId?: string): Promise<number> { if (!subscriptionId) return 0; return (await dashboard()).pmsListings.length; }
export async function getMyPMSListings(): Promise<PMSListing[]> { return (await dashboard()).pmsListings; }
export async function getMyAvailablePMSListings(): Promise<PMSAvailableListing[]> { return (await dashboard()).availableListings; }
export async function getMyPMSUnits(listingId: string): Promise<PMSUnit[]> { if (!listingId) return []; return (await dashboard()).units.filter(x => x.listing_id === listingId); }
export async function getMyAllPMSUnits(_pmsListings?: PMSListing[]): Promise<PMSUnit[]> { return (await dashboard()).units; }
export async function isListingPMSManaged(listingId: string): Promise<boolean> { return (await dashboard()).pmsListings.some(x => x.listing_id === listingId); }
export async function addListingToPMS(subscriptionId: string, listingId: string): Promise<unknown> { if (!subscriptionId) throw new Error('An active PMS subscription is required.'); if (!listingId) throw new Error('A listing is required.'); return action({ action: 'add_listing', subscription_id: subscriptionId, listing_id: listingId }); }
export async function removeListingFromPMS(subscriptionId: string, listingId: string): Promise<unknown> { if (!subscriptionId) throw new Error('A PMS subscription is required.'); if (!listingId) throw new Error('A listing is required.'); return action({ action: 'remove_listing', subscription_id: subscriptionId, listing_id: listingId }); }
export const getPMSPlans = () => protectedGet<PMSPlan[]>('/api/subscriptions/plans/?audience=LANDLORD');
export async function getMyLandlordListings(): Promise<LandlordListing[]> { const raw = await protectedGet<{ results?: LandlordListing[] }>('/api/listings/?limit=100&offset=0'); return raw?.results ?? []; }
export async function getMyListingPayments(): Promise<ListingPayment[]> { return (await dashboard()).listingPayments; }
export async function getMyLandlordPaymentMethods(): Promise<LandlordPaymentMethod[]> { return (await dashboard()).paymentMethods; }
export async function setLandlordPaymentMethodDefault(paymentMethodId: string): Promise<void> { if (!paymentMethodId) throw new Error('A payment method is required.'); await action({ action: 'set_payment_method_default', payment_method_id: paymentMethodId }); }
export async function getMyPMSNotifications(): Promise<PMSNotification[]> { return (await dashboard()).notifications; }
export async function markUserNotificationRead(notificationId: string): Promise<void> { await action({ action: 'mark_user_notification_read', notification_id: notificationId }); }
export async function markPMSNotificationRead(notificationId: string): Promise<void> { await action({ action: 'mark_pms_notification_read', notification_id: notificationId }); }
export async function getMySubscriptionInvoices(_subscriptionId?: string): Promise<PMSSubscriptionInvoice[]> { return (await dashboard()).subscriptionInvoices; }
export async function getMyRentInvoices(): Promise<LandlordRentInvoice[]> { return (await dashboard()).rentInvoices; }
export async function getMyRentPayments(): Promise<LandlordRentPayment[]> { return (await dashboard()).rentPayments; }
export async function getMyPendingRentSubmissions(): Promise<RentPaymentSubmission[]> { return (await dashboard()).pendingRentSubmissions; }
export function summarizeLandlordListings(listings: LandlordListing[], pmsListings: PMSListing[]): LandlordListingSummary { const pmsIds = new Set(pmsListings.map(x => x.listing_id)); return { total: listings.length, published: listings.filter(x => x.is_published).length, unpublished: listings.filter(x => !x.is_published).length, approved: listings.filter(x => x.is_approved || x.approval_status?.toLowerCase() === 'approved').length, pending_approval: listings.filter(x => !x.is_approved && !['approved', 'rejected', 'declined'].includes(x.approval_status?.toLowerCase() ?? '')).length, rejected: listings.filter(x => ['rejected', 'declined'].includes(x.approval_status?.toLowerCase() ?? '')).length, paid: listings.filter(x => x.is_paid).length, unpaid: listings.filter(x => !x.is_paid).length, pms_managed: listings.filter(x => pmsIds.has(x.id)).length }; }
export function computeRentSummary(invoices: LandlordRentInvoice[], payments: LandlordRentPayment[], submissions: RentPaymentSubmission[]): LandlordRentSummary { const paid = invoices.filter(x => x.status.toUpperCase() === 'PAID'); const pending = invoices.filter(x => ['PENDING', 'OPEN', 'UNPAID', 'PROCESSING', 'DUE'].includes(x.status.toUpperCase())); const overdue = invoices.filter(x => x.status.toUpperCase() === 'OVERDUE' || (x.status.toUpperCase() !== 'PAID' && new Date(x.due_date) < new Date())); return { invoice_count: invoices.length, total_invoiced_kes: invoices.reduce((s, x) => s + Number(x.amount_kes), 0), paid_invoice_count: paid.length, paid_amount_kes: paid.reduce((s, x) => s + Number(x.amount_kes), 0), pending_invoice_count: pending.length, pending_amount_kes: pending.reduce((s, x) => s + Number(x.amount_kes), 0), overdue_invoice_count: overdue.length, overdue_amount_kes: overdue.reduce((s, x) => s + Number(x.amount_kes), 0), pending_submission_count: submissions.filter(x => x.status.toUpperCase() === 'PENDING').length, payment_count: payments.length, total_payments_kes: payments.filter(x => x.status.toUpperCase() === 'PAID').reduce((s, x) => s + Number(x.amount_kes), 0) }; }
export async function createLandlordListing(input: CreateLandlordListingInput): Promise<unknown> { return protectedPost('/api/listings/create/', input); }
export async function createListingPaymentIntent(listingData: Record<string, unknown>): Promise<unknown> { return protectedPost('/api/listings/payment-intents/', listingData); }
export async function initiatePMSPayment(request: PMSPaymentRequest): Promise<PMSPaymentResponse> { const data = await protectedPost<PMSPaymentResponse>('/api/subscriptions/checkout/', { plan_id: request.plan_id, billing_cycle: request.billing_cycle, provider: 'MPESA' }); if (!data?.success) throw new Error(data?.error || data?.message || 'Unable to initiate M-Pesa payment.'); return data; }
export const loadPMSDashboardData = dashboard;
