# Generated by Django 6.0.8 on 2026-09-03 13:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('middle_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('role', models.CharField(default='renter', max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
                ('kyc_completed', models.BooleanField(default=False)),
                ('verification_status', models.CharField(default='pending_verification', max_length=50)),
                ('kyc_status', models.CharField(default='pending', max_length=50)),
                ('landlord_application_status', models.CharField(default='not_requested', max_length=50)),
                ('real_estate_application_status', models.CharField(default='not_requested', max_length=50)),
                ('mover_application_status', models.CharField(default='not_requested', max_length=50)),
                ('national_id', models.CharField(blank=True, default='', max_length=100)),
                ('dl_number', models.CharField(blank=True, default='', max_length=100)),
                ('profile_photo_url', models.TextField(blank=True, default='')),
                ('id_photo_url', models.TextField(blank=True, default='')),
                ('selfie_url', models.TextField(blank=True, default='')),
                ('id_document_url', models.TextField(blank=True, default='')),
                ('id_document_type', models.CharField(blank=True, default='', max_length=30)),
                ('city', models.CharField(blank=True, default='', max_length=150)),
                ('county', models.CharField(blank=True, default='', max_length=150)),
                ('is_agency', models.BooleanField(default=False)),
                ('free_listings_used', models.PositiveIntegerField(default=0)),
                ('email_verified', models.BooleanField(default=False)),
                ('admin_review_note', models.TextField(blank=True, default='')),
                ('role_selected_at', models.DateTimeField(blank=True, null=True)),
                ('signup_otp_hash', models.TextField(blank=True, null=True)),
                ('signup_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('signup_otp_attempts', models.PositiveIntegerField(default=0)),
                ('signup_otp_last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('signup_otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('signup_otp_encrypted', models.TextField(blank=True, null=True)),
                ('signup_otp_trial_count', models.PositiveIntegerField(default=0)),
                ('signup_verification_started_at', models.DateTimeField(blank=True, null=True)),
                ('signup_verification_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('google_subject', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('jti', models.UUIDField(primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('replaced_by', models.UUIDField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_refresh_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role'], name='profiles_role_a79c05_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['verification_status'], name='profiles_verific_7afbb0_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['kyc_status'], name='profiles_kyc_sta_664430_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user', 'revoked_at'], name='django_refr_user_id_26df20_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['expires_at'], name='django_refr_expires_c21f01_idx'),
        ),
    ]
