# Generated by Django 6.0.8 on 2026-09-03 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_kes', models.DecimalField(decimal_places=2, default=1000, max_digits=14)),
                ('mpesa_receipt', models.TextField(blank=True, null=True)),
                ('checkout_request_id', models.TextField(blank=True, null=True)),
                ('merchant_request_id', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='PENDING')),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_provider', models.TextField(blank=True, null=True)),
                ('payment_method', models.TextField(blank=True, null=True)),
                ('provider_reference', models.TextField(blank=True, null=True)),
                ('provider_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('provider_currency', models.TextField(blank=True, null=True)),
                ('paypal_order_id', models.TextField(blank=True, null=True)),
                ('paypal_fx_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('listing', models.ForeignKey(db_column='listing_id', on_delete=django.db.models.deletion.PROTECT, related_name='listing_payments', to='listings.listing')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='listing_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listing_payments',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_kes__gt', 0)), name='listing_payments_amount_check'), models.CheckConstraint(condition=models.Q(('amount_kes', 1000)), name='listing_payments_amount_fixed_check'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'PAID', 'FAILED', 'CANCELLED'])), name='listing_payments_status_check'), models.CheckConstraint(condition=models.Q(('payment_provider__isnull', True), ('payment_provider__in', ['MPESA', 'PAYPAL']), _connector='OR'), name='listing_payments_provider_check'), models.CheckConstraint(condition=models.Q(('payment_method__isnull', True), ('payment_method__in', ['MPESA', 'PAYPAL']), _connector='OR'), name='listing_payments_method_check'), models.UniqueConstraint(fields=('checkout_request_id',), name='listing_payments_checkout_request_id_key'), models.UniqueConstraint(fields=('provider_reference',), name='listing_payments_provider_reference_key')],
            },
        ),
    ]
