import { ThemeProvider } from '@/context/ThemeContext';
import { AuthProvider, useAuth } from '@/context/AuthContext';
import { NavProvider, useNav } from '@/context/NavContext';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import BottomBar from '@/components/BottomBar';
import SecurityBanner from '@/components/SecurityBanner';
import AuthModal from '@/components/AuthModal';
import RoleSelectionModal from '@/components/RoleSelectionModal';
import MovingGpsTracker from '@/components/MovingGpsTracker';
import HomePage from '@/pages/HomePage';
import ListingsPage from '@/pages/ListingsPage';
import ListingDetailPage from '@/pages/ListingDetailPage';
import MoversPage from '@/pages/MoversPage';
import MoverDetailPage from '@/pages/MoverDetailPage';
import MoverBookingDetailPage from '@/pages/MoverBookingDetailPage';
import ChatPage from '@/pages/ChatPage';
import CommunityPage from '@/pages/CommunityPage';
import PostListingPage from '@/pages/PostListingPageV2';
import RegisterLandlordPage from '@/pages/RegisterLandlordPage';
import KycVerifyPage from '@/pages/KycVerifyPage';
import MoverTrackingPage from '@/components/RentersComponentPage/MoverTrackingPage';
import RoleDashboardRouter from '@/Dashboards/RoleDashboardRouter';
import DashboardPage from '@/Dashboards/DashboardPage';
import AdminUserDetailsRoute from '@/pages/AdminUserDetailsRoute';
import ProfilePage from '@/pages/ProfilePage';
import ListingManagePage from './pages/ListingManagePage';
import PMSSubscriptionPage from './components/PMS/PMSSubscriptionPage';
import RegisterMoverPage from './pages/RegisterMoverPage';
import MoverCalendarPage from './pages/Movers/MoverCalendarPage';
import MoverBookingRequestsPage from './pages/Movers/MoverBookingRequestsPage';
import MoverUpcomingJobsPage from './pages/Movers/MoverUpcomingJobsPage';
import MoverCustomers from './pages/Movers/MoverCustomers';
import MoverInvoices from './pages/Movers/MoverInvoices';
import MoverEarnings from './pages/Movers/MoverEarnings';
import MoverNotifications from './pages/Movers/MoverNotifications';
import MoverMessages from './pages/Movers/MoverMessages';
import PayPalSubscriptionReturnPage from './pages/PayPalSubscriptionReturnPage';
import PayPalSubscriptionCancelPage from './pages/PayPalSubscriptionCancelPage';
import ListingPaymentReturnPage from './pages/ListingPaymentReturnPage';

function AppContent() {
  const { view, selectedAdminUserId } = useNav();
  const { profile } = useAuth();
  if (window.location.pathname === '/paypal/subscription/return') return <PayPalSubscriptionReturnPage />;
  if (window.location.pathname === '/paypal/subscription/cancel') return <PayPalSubscriptionCancelPage />;
  if (window.location.pathname === '/listing/payment/return') return <ListingPaymentReturnPage />;
  const renderView = () => {
    switch (view) {
      case 'home': return <HomePage />;
      case 'listings': return <ListingsPage />;
      case 'listing-detail': return <ListingDetailPage />;
      case 'listing-manage': return <ListingManagePage />;
      case 'movers': return <MoversPage />;
      case 'mover-detail': return <MoverDetailPage />;
      case 'mover-booking-detail': return <MoverBookingDetailPage />;
      case 'mover-tracking': return <MoverTrackingPage />;
      case 'mover-calendar': return <MoverCalendarPage />;
      case 'mover-booking-requests': return <MoverBookingRequestsPage />;
      case 'mover-upcoming-jobs': return <MoverUpcomingJobsPage />;
      case 'mover-customers': return <MoverCustomers />;
      case 'mover-invoices': return <MoverInvoices />;
      case 'mover-earnings': return <MoverEarnings />;
      case 'mover-notifications': return <MoverNotifications />;
      case 'mover-messages': return <MoverMessages />;
      case 'chat': return <ChatPage />;
      case 'community': return <CommunityPage />;
      case 'post-listing': return <PostListingPage />;
      case 'register-mover': return <RegisterMoverPage />;
      case 'register-landlord': return <RegisterLandlordPage />;
      case 'kyc-verify': return <KycVerifyPage />;
      case 'admin-user-details': return (profile?.is_superuser === true || profile?.is_admin === true) ? (selectedAdminUserId ? <AdminUserDetailsRoute userId={selectedAdminUserId} onBack={() => window.history.back()} /> : <DashboardPage />) : <DashboardPage />;
      case 'dashboard': return <RoleDashboardRouter />;
      case 'profile': return <ProfilePage />;
      case 'my-bookings': return <DashboardPage />;
      case 'my-listings': return <DashboardPage />;
      case 'subscription-plans': return <PMSSubscriptionPage />;
      default: return <HomePage />;
    }
  };
  return <div className="flex min-h-screen flex-col overflow-hidden bg-gray-50 dark:bg-brand-950"><SecurityBanner /><Header /><main className="flex-1 pb-20 md:pb-0">{renderView()}</main><Footer /><BottomBar /><AuthModal /><RoleSelectionModal /><MovingGpsTracker /></div>;
}
export default function App() { return <ThemeProvider><AuthProvider><NavProvider><AppContent /></NavProvider></AuthProvider></ThemeProvider>; }
